/*
 * 团购活动详情
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.models;

import java.util.Objects;
import java.util.Arrays;
import com.douyin.open.models.EnterpriseGrouponGrouponGrouponDetailGrouponItem;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * EnterpriseGrouponGrouponGrouponDetailInlineResponse200Data
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-13T12:07:48.970677+08:00[Asia/Shanghai]")
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public class EnterpriseGrouponGrouponGrouponDetailInlineResponse200Data {
  @JsonProperty("error_code")
  private Integer errorCode = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("groupons")
  private List<EnterpriseGrouponGrouponGrouponDetailGrouponItem> groupons = null;

  public EnterpriseGrouponGrouponGrouponDetailInlineResponse200Data errorCode(Integer errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  @Schema(required = true, description = "")
  public Integer getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(Integer errorCode) {
    this.errorCode = errorCode;
  }

  public EnterpriseGrouponGrouponGrouponDetailInlineResponse200Data description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(required = true, description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public EnterpriseGrouponGrouponGrouponDetailInlineResponse200Data groupons(List<EnterpriseGrouponGrouponGrouponDetailGrouponItem> groupons) {
    this.groupons = groupons;
    return this;
  }

  public EnterpriseGrouponGrouponGrouponDetailInlineResponse200Data addGrouponsItem(EnterpriseGrouponGrouponGrouponDetailGrouponItem grouponsItem) {
    if (this.groupons == null) {
      this.groupons = new ArrayList<>();
    }
    this.groupons.add(grouponsItem);
    return this;
  }

   /**
   * Get groupons
   * @return groupons
  **/
  @Schema(example = "{\"groupon_id\":\"dsfadfasdf-123rdfadsf\",\"use_type\":1,\"code_type\":1,\"merchant_name\":\"展示的商家名称\",\"title\":\"团购活动示例\",\"cover_images\":[\"sdfasdfasdf\",\"sdfasdfasdfasd\"],\"notification\":\"下单后不支持退货\\n\",\"stock\":100,\"order_limit\":3,\"service_number\":\"400-000-000\",\"sold_count\":60,\"audit_msg\":\"标题包含敏感信息\",\"groupon_goods\":[{\"name\":\"团购活动商品1\",\"price\":400},{\"name\":\"团购活动商品2\",\"price\":500}],\"start_time\":1585049963,\"ent_time\":1585549964}", description = "")
  public List<EnterpriseGrouponGrouponGrouponDetailGrouponItem> getGroupons() {
    return groupons;
  }

  public void setGroupons(List<EnterpriseGrouponGrouponGrouponDetailGrouponItem> groupons) {
    this.groupons = groupons;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnterpriseGrouponGrouponGrouponDetailInlineResponse200Data inlineResponse200Data = (EnterpriseGrouponGrouponGrouponDetailInlineResponse200Data) o;
    return Objects.equals(this.errorCode, inlineResponse200Data.errorCode) &&
        Objects.equals(this.description, inlineResponse200Data.description) &&
        Objects.equals(this.groupons, inlineResponse200Data.groupons);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorCode, description, groupons);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnterpriseGrouponGrouponGrouponDetailInlineResponse200Data {\n");
    
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    groupons: ").append(toIndentedString(groupons)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
