/*
 * 企业号意向用户管理
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.models;

import java.util.Objects;
import java.util.Arrays;
import com.douyin.open.models.EnterpriseLeadsLeadsUserInlineResponse200DataTagList;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * EnterpriseLeadsLeadsUserInlineResponse200DataUsers
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-13T12:06:36.469880+08:00[Asia/Shanghai]")
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public class EnterpriseLeadsLeadsUserInlineResponse200DataUsers {
  @JsonProperty("open_id")
  private String openId = null;

  @JsonProperty("nickname")
  private String nickname = null;

  @JsonProperty("avatar")
  private String avatar = null;

  @JsonProperty("telephone")
  private String telephone = null;

  @JsonProperty("wechat")
  private String wechat = null;

  @JsonProperty("city")
  private String city = null;

  /**
   * 性别 * &#x60;0&#x60; - 未知 * &#x60;1&#x60; - 男 * &#x60;2&#x60; - 女 
   */
  public enum GenderEnum {
    NUMBER_0(0),
    NUMBER_1(1),
    NUMBER_2(2);

    private Integer value;

    GenderEnum(Integer value) {
      this.value = value;
    }
    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static GenderEnum fromValue(String text) {
      for (GenderEnum b : GenderEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("gender")
  private GenderEnum gender = null;

  @JsonProperty("age")
  private Integer age = null;

  /**
   * 用户状态 * &#x60;-1&#x60; - 没兴趣 * &#x60;0&#x60; - 了解 * &#x60;1&#x60; - 有兴趣 * &#x60;2&#x60; - 有意愿 * &#x60;10&#x60; - 已转化 
   */
  public enum LeadsLevelEnum {
    NUMBER_MINUS_1(-1),
    NUMBER_0(0),
    NUMBER_1(1),
    NUMBER_2(2),
    NUMBER_10(10);

    private Integer value;

    LeadsLevelEnum(Integer value) {
      this.value = value;
    }
    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static LeadsLevelEnum fromValue(String text) {
      for (LeadsLevelEnum b : LeadsLevelEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("leads_level")
  private LeadsLevelEnum leadsLevel = null;

  @JsonProperty("tag_list")
  private List<EnterpriseLeadsLeadsUserInlineResponse200DataTagList> tagList = null;

  @JsonProperty("is_follow")
  private Boolean isFollow = null;

  public EnterpriseLeadsLeadsUserInlineResponse200DataUsers openId(String openId) {
    this.openId = openId;
    return this;
  }

   /**
   * 用户在当前应用的唯一标识
   * @return openId
  **/
  @Schema(example = "15674132978", description = "用户在当前应用的唯一标识")
  public String getOpenId() {
    return openId;
  }

  public void setOpenId(String openId) {
    this.openId = openId;
  }

  public EnterpriseLeadsLeadsUserInlineResponse200DataUsers nickname(String nickname) {
    this.nickname = nickname;
    return this;
  }

   /**
   * Get nickname
   * @return nickname
  **/
  @Schema(example = "jack", description = "")
  public String getNickname() {
    return nickname;
  }

  public void setNickname(String nickname) {
    this.nickname = nickname;
  }

  public EnterpriseLeadsLeadsUserInlineResponse200DataUsers avatar(String avatar) {
    this.avatar = avatar;
    return this;
  }

   /**
   * Get avatar
   * @return avatar
  **/
  @Schema(example = "url", description = "")
  public String getAvatar() {
    return avatar;
  }

  public void setAvatar(String avatar) {
    this.avatar = avatar;
  }

  public EnterpriseLeadsLeadsUserInlineResponse200DataUsers telephone(String telephone) {
    this.telephone = telephone;
    return this;
  }

   /**
   * Get telephone
   * @return telephone
  **/
  @Schema(description = "")
  public String getTelephone() {
    return telephone;
  }

  public void setTelephone(String telephone) {
    this.telephone = telephone;
  }

  public EnterpriseLeadsLeadsUserInlineResponse200DataUsers wechat(String wechat) {
    this.wechat = wechat;
    return this;
  }

   /**
   * Get wechat
   * @return wechat
  **/
  @Schema(description = "")
  public String getWechat() {
    return wechat;
  }

  public void setWechat(String wechat) {
    this.wechat = wechat;
  }

  public EnterpriseLeadsLeadsUserInlineResponse200DataUsers city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @Schema(description = "")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public EnterpriseLeadsLeadsUserInlineResponse200DataUsers gender(GenderEnum gender) {
    this.gender = gender;
    return this;
  }

   /**
   * 性别 * &#x60;0&#x60; - 未知 * &#x60;1&#x60; - 男 * &#x60;2&#x60; - 女 
   * @return gender
  **/
  @Schema(description = "性别 * `0` - 未知 * `1` - 男 * `2` - 女 ")
  public GenderEnum getGender() {
    return gender;
  }

  public void setGender(GenderEnum gender) {
    this.gender = gender;
  }

  public EnterpriseLeadsLeadsUserInlineResponse200DataUsers age(Integer age) {
    this.age = age;
    return this;
  }

   /**
   * Get age
   * @return age
  **/
  @Schema(description = "")
  public Integer getAge() {
    return age;
  }

  public void setAge(Integer age) {
    this.age = age;
  }

  public EnterpriseLeadsLeadsUserInlineResponse200DataUsers leadsLevel(LeadsLevelEnum leadsLevel) {
    this.leadsLevel = leadsLevel;
    return this;
  }

   /**
   * 用户状态 * &#x60;-1&#x60; - 没兴趣 * &#x60;0&#x60; - 了解 * &#x60;1&#x60; - 有兴趣 * &#x60;2&#x60; - 有意愿 * &#x60;10&#x60; - 已转化 
   * @return leadsLevel
  **/
  @Schema(description = "用户状态 * `-1` - 没兴趣 * `0` - 了解 * `1` - 有兴趣 * `2` - 有意愿 * `10` - 已转化 ")
  public LeadsLevelEnum getLeadsLevel() {
    return leadsLevel;
  }

  public void setLeadsLevel(LeadsLevelEnum leadsLevel) {
    this.leadsLevel = leadsLevel;
  }

  public EnterpriseLeadsLeadsUserInlineResponse200DataUsers tagList(List<EnterpriseLeadsLeadsUserInlineResponse200DataTagList> tagList) {
    this.tagList = tagList;
    return this;
  }

  public EnterpriseLeadsLeadsUserInlineResponse200DataUsers addTagListItem(EnterpriseLeadsLeadsUserInlineResponse200DataTagList tagListItem) {
    if (this.tagList == null) {
      this.tagList = new ArrayList<>();
    }
    this.tagList.add(tagListItem);
    return this;
  }

   /**
   * 绑定的标签列表
   * @return tagList
  **/
  @Schema(description = "绑定的标签列表")
  public List<EnterpriseLeadsLeadsUserInlineResponse200DataTagList> getTagList() {
    return tagList;
  }

  public void setTagList(List<EnterpriseLeadsLeadsUserInlineResponse200DataTagList> tagList) {
    this.tagList = tagList;
  }

  public EnterpriseLeadsLeadsUserInlineResponse200DataUsers isFollow(Boolean isFollow) {
    this.isFollow = isFollow;
    return this;
  }

   /**
   * 当前指定用户是否已关注本企业号
   * @return isFollow
  **/
  @Schema(example = "true", description = "当前指定用户是否已关注本企业号")
  public Boolean isIsFollow() {
    return isFollow;
  }

  public void setIsFollow(Boolean isFollow) {
    this.isFollow = isFollow;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnterpriseLeadsLeadsUserInlineResponse200DataUsers inlineResponse200DataUsers = (EnterpriseLeadsLeadsUserInlineResponse200DataUsers) o;
    return Objects.equals(this.openId, inlineResponse200DataUsers.openId) &&
        Objects.equals(this.nickname, inlineResponse200DataUsers.nickname) &&
        Objects.equals(this.avatar, inlineResponse200DataUsers.avatar) &&
        Objects.equals(this.telephone, inlineResponse200DataUsers.telephone) &&
        Objects.equals(this.wechat, inlineResponse200DataUsers.wechat) &&
        Objects.equals(this.city, inlineResponse200DataUsers.city) &&
        Objects.equals(this.gender, inlineResponse200DataUsers.gender) &&
        Objects.equals(this.age, inlineResponse200DataUsers.age) &&
        Objects.equals(this.leadsLevel, inlineResponse200DataUsers.leadsLevel) &&
        Objects.equals(this.tagList, inlineResponse200DataUsers.tagList) &&
        Objects.equals(this.isFollow, inlineResponse200DataUsers.isFollow);
  }

  @Override
  public int hashCode() {
    return Objects.hash(openId, nickname, avatar, telephone, wechat, city, gender, age, leadsLevel, tagList, isFollow);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnterpriseLeadsLeadsUserInlineResponse200DataUsers {\n");
    
    sb.append("    openId: ").append(toIndentedString(openId)).append("\n");
    sb.append("    nickname: ").append(toIndentedString(nickname)).append("\n");
    sb.append("    avatar: ").append(toIndentedString(avatar)).append("\n");
    sb.append("    telephone: ").append(toIndentedString(telephone)).append("\n");
    sb.append("    wechat: ").append(toIndentedString(wechat)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    age: ").append(toIndentedString(age)).append("\n");
    sb.append("    leadsLevel: ").append(toIndentedString(leadsLevel)).append("\n");
    sb.append("    tagList: ").append(toIndentedString(tagList)).append("\n");
    sb.append("    isFollow: ").append(toIndentedString(isFollow)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
