/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ExternalDataUserExternalDataUserExternalUserComment
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-13T12:05:40.426937+08:00[Asia/Shanghai]")
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public class ExternalDataUserExternalDataUserExternalUserComment {
  @JsonProperty("date")
  private String date = null;

  @JsonProperty("new_comment")
  private Integer newComment = null;

  public ExternalDataUserExternalDataUserExternalUserComment date(String date) {
    this.date = date;
    return this;
  }

   /**
   * 日期
   * @return date
  **/
  @Schema(example = "yyyy-MM-dd", description = "日期")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public ExternalDataUserExternalDataUserExternalUserComment newComment(Integer newComment) {
    this.newComment = newComment;
    return this;
  }

   /**
   * 新增评论
   * @return newComment
  **/
  @Schema(example = "200", description = "新增评论")
  public Integer getNewComment() {
    return newComment;
  }

  public void setNewComment(Integer newComment) {
    this.newComment = newComment;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalDataUserExternalDataUserExternalUserComment externalUserComment = (ExternalDataUserExternalDataUserExternalUserComment) o;
    return Objects.equals(this.date, externalUserComment.date) &&
        Objects.equals(this.newComment, externalUserComment.newComment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, newComment);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalDataUserExternalDataUserExternalUserComment {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    newComment: ").append(toIndentedString(newComment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
