/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ExternalDataUserExternalDataUserExternalUserFans
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-13T12:05:40.426937+08:00[Asia/Shanghai]")
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public class ExternalDataUserExternalDataUserExternalUserFans {
  @JsonProperty("date")
  private String date = null;

  @JsonProperty("total_fans")
  private Integer totalFans = null;

  @JsonProperty("new_fans")
  private Integer newFans = null;

  public ExternalDataUserExternalDataUserExternalUserFans date(String date) {
    this.date = date;
    return this;
  }

   /**
   * 日期
   * @return date
  **/
  @Schema(example = "yyyy-MM-dd", description = "日期")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public ExternalDataUserExternalDataUserExternalUserFans totalFans(Integer totalFans) {
    this.totalFans = totalFans;
    return this;
  }

   /**
   * 每日总粉丝数
   * @return totalFans
  **/
  @Schema(example = "200", description = "每日总粉丝数")
  public Integer getTotalFans() {
    return totalFans;
  }

  public void setTotalFans(Integer totalFans) {
    this.totalFans = totalFans;
  }

  public ExternalDataUserExternalDataUserExternalUserFans newFans(Integer newFans) {
    this.newFans = newFans;
    return this;
  }

   /**
   * 每天新粉丝数
   * @return newFans
  **/
  @Schema(example = "200", description = "每天新粉丝数")
  public Integer getNewFans() {
    return newFans;
  }

  public void setNewFans(Integer newFans) {
    this.newFans = newFans;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalDataUserExternalDataUserExternalUserFans externalUserFans = (ExternalDataUserExternalDataUserExternalUserFans) o;
    return Objects.equals(this.date, externalUserFans.date) &&
        Objects.equals(this.totalFans, externalUserFans.totalFans) &&
        Objects.equals(this.newFans, externalUserFans.newFans);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, totalFans, newFans);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalDataUserExternalDataUserExternalUserFans {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    totalFans: ").append(toIndentedString(totalFans)).append("\n");
    sb.append("    newFans: ").append(toIndentedString(newFans)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
