/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ExternalDataUserExternalDataUserExternalUserLike
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-13T12:05:40.426937+08:00[Asia/Shanghai]")
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public class ExternalDataUserExternalDataUserExternalUserLike {
  @JsonProperty("date")
  private String date = null;

  @JsonProperty("new_like")
  private Integer newLike = null;

  public ExternalDataUserExternalDataUserExternalUserLike date(String date) {
    this.date = date;
    return this;
  }

   /**
   * 日期
   * @return date
  **/
  @Schema(example = "yyyy-MM-dd", description = "日期")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public ExternalDataUserExternalDataUserExternalUserLike newLike(Integer newLike) {
    this.newLike = newLike;
    return this;
  }

   /**
   * 新增点赞
   * @return newLike
  **/
  @Schema(example = "200", description = "新增点赞")
  public Integer getNewLike() {
    return newLike;
  }

  public void setNewLike(Integer newLike) {
    this.newLike = newLike;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalDataUserExternalDataUserExternalUserLike externalUserLike = (ExternalDataUserExternalDataUserExternalUserLike) o;
    return Objects.equals(this.date, externalUserLike.date) &&
        Objects.equals(this.newLike, externalUserLike.newLike);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, newLike);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalDataUserExternalDataUserExternalUserLike {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    newLike: ").append(toIndentedString(newLike)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
