/*
 * 
 * 获取用户的粉丝数据
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * FansDataFansDataFansProfileDistribution
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-13T12:05:56.403420+08:00[Asia/Shanghai]")
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public class FansDataFansDataFansProfileDistribution {
  @JsonProperty("item")
  private String item = null;

  @JsonProperty("value")
  private Integer value = null;

  public FansDataFansDataFansProfileDistribution item(String item) {
    this.item = item;
    return this;
  }

   /**
   * 分布的种类
   * @return item
  **/
  @Schema(required = true, description = "分布的种类")
  public String getItem() {
    return item;
  }

  public void setItem(String item) {
    this.item = item;
  }

  public FansDataFansDataFansProfileDistribution value(Integer value) {
    this.value = value;
    return this;
  }

   /**
   * 分布的数值
   * @return value
  **/
  @Schema(required = true, description = "分布的数值")
  public Integer getValue() {
    return value;
  }

  public void setValue(Integer value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FansDataFansDataFansProfileDistribution fansProfileDistribution = (FansDataFansDataFansProfileDistribution) o;
    return Objects.equals(this.item, fansProfileDistribution.item) &&
        Objects.equals(this.value, fansProfileDistribution.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(item, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FansDataFansDataFansProfileDistribution {\n");
    
    sb.append("    item: ").append(toIndentedString(item)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
