/*
 * 
 * 获取用户的粉丝数据
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * FansDataFansDataFansProfileFlowContribution
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-13T12:05:56.403420+08:00[Asia/Shanghai]")
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public class FansDataFansDataFansProfileFlowContribution {
  @JsonProperty("flow")
  private String flow = null;

  @JsonProperty("fans_sum")
  private Integer fansSum = null;

  @JsonProperty("all_sum")
  private Integer allSum = null;

  public FansDataFansDataFansProfileFlowContribution flow(String flow) {
    this.flow = flow;
    return this;
  }

   /**
   * 流量贡献种类
   * @return flow
  **/
  @Schema(required = true, description = "流量贡献种类")
  public String getFlow() {
    return flow;
  }

  public void setFlow(String flow) {
    this.flow = flow;
  }

  public FansDataFansDataFansProfileFlowContribution fansSum(Integer fansSum) {
    this.fansSum = fansSum;
    return this;
  }

   /**
   * 粉丝流量贡献
   * @return fansSum
  **/
  @Schema(required = true, description = "粉丝流量贡献")
  public Integer getFansSum() {
    return fansSum;
  }

  public void setFansSum(Integer fansSum) {
    this.fansSum = fansSum;
  }

  public FansDataFansDataFansProfileFlowContribution allSum(Integer allSum) {
    this.allSum = allSum;
    return this;
  }

   /**
   * 总流量贡献
   * @return allSum
  **/
  @Schema(required = true, description = "总流量贡献")
  public Integer getAllSum() {
    return allSum;
  }

  public void setAllSum(Integer allSum) {
    this.allSum = allSum;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FansDataFansDataFansProfileFlowContribution fansProfileFlowContribution = (FansDataFansDataFansProfileFlowContribution) o;
    return Objects.equals(this.flow, fansProfileFlowContribution.flow) &&
        Objects.equals(this.fansSum, fansProfileFlowContribution.fansSum) &&
        Objects.equals(this.allSum, fansProfileFlowContribution.allSum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(flow, fansSum, allSum);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FansDataFansDataFansProfileFlowContribution {\n");
    
    sb.append("    flow: ").append(toIndentedString(flow)).append("\n");
    sb.append("    fansSum: ").append(toIndentedString(fansSum)).append("\n");
    sb.append("    allSum: ").append(toIndentedString(allSum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
