/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
/**
 * PoiBaseBaseInlineResponse200Data
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-13T12:09:21.574824+08:00[Asia/Shanghai]")
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public class PoiBaseBaseInlineResponse200Data {
  @JsonProperty("poi_id")
  private String poiId = null;

  @JsonProperty("poi_name")
  private String poiName = null;

  @JsonProperty("amap_id")
  private String amapId = null;

  @JsonProperty("address")
  private String address = null;

  @JsonProperty("city")
  private String city = null;

  @JsonProperty("latitude")
  private BigDecimal latitude = null;

  @JsonProperty("longitude")
  private BigDecimal longitude = null;

  @JsonProperty("error_code")
  private Integer errorCode = null;

  @JsonProperty("description")
  private String description = null;

  public PoiBaseBaseInlineResponse200Data poiId(String poiId) {
    this.poiId = poiId;
    return this;
  }

   /**
   * 抖音POI ID
   * @return poiId
  **/
  @Schema(required = true, description = "抖音POI ID")
  public String getPoiId() {
    return poiId;
  }

  public void setPoiId(String poiId) {
    this.poiId = poiId;
  }

  public PoiBaseBaseInlineResponse200Data poiName(String poiName) {
    this.poiName = poiName;
    return this;
  }

   /**
   * POI 名称
   * @return poiName
  **/
  @Schema(required = true, description = "POI 名称")
  public String getPoiName() {
    return poiName;
  }

  public void setPoiName(String poiName) {
    this.poiName = poiName;
  }

  public PoiBaseBaseInlineResponse200Data amapId(String amapId) {
    this.amapId = amapId;
    return this;
  }

   /**
   * 高德POI ID
   * @return amapId
  **/
  @Schema(required = true, description = "高德POI ID")
  public String getAmapId() {
    return amapId;
  }

  public void setAmapId(String amapId) {
    this.amapId = amapId;
  }

  public PoiBaseBaseInlineResponse200Data address(String address) {
    this.address = address;
    return this;
  }

   /**
   * POI地址
   * @return address
  **/
  @Schema(required = true, description = "POI地址")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public PoiBaseBaseInlineResponse200Data city(String city) {
    this.city = city;
    return this;
  }

   /**
   * POI所在城市
   * @return city
  **/
  @Schema(required = true, description = "POI所在城市")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public PoiBaseBaseInlineResponse200Data latitude(BigDecimal latitude) {
    this.latitude = latitude;
    return this;
  }

   /**
   * 纬度
   * @return latitude
  **/
  @Schema(required = true, description = "纬度")
  public BigDecimal getLatitude() {
    return latitude;
  }

  public void setLatitude(BigDecimal latitude) {
    this.latitude = latitude;
  }

  public PoiBaseBaseInlineResponse200Data longitude(BigDecimal longitude) {
    this.longitude = longitude;
    return this;
  }

   /**
   * 经度
   * @return longitude
  **/
  @Schema(required = true, description = "经度")
  public BigDecimal getLongitude() {
    return longitude;
  }

  public void setLongitude(BigDecimal longitude) {
    this.longitude = longitude;
  }

  public PoiBaseBaseInlineResponse200Data errorCode(Integer errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  @Schema(required = true, description = "")
  public Integer getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(Integer errorCode) {
    this.errorCode = errorCode;
  }

  public PoiBaseBaseInlineResponse200Data description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(required = true, description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PoiBaseBaseInlineResponse200Data inlineResponse200Data = (PoiBaseBaseInlineResponse200Data) o;
    return Objects.equals(this.poiId, inlineResponse200Data.poiId) &&
        Objects.equals(this.poiName, inlineResponse200Data.poiName) &&
        Objects.equals(this.amapId, inlineResponse200Data.amapId) &&
        Objects.equals(this.address, inlineResponse200Data.address) &&
        Objects.equals(this.city, inlineResponse200Data.city) &&
        Objects.equals(this.latitude, inlineResponse200Data.latitude) &&
        Objects.equals(this.longitude, inlineResponse200Data.longitude) &&
        Objects.equals(this.errorCode, inlineResponse200Data.errorCode) &&
        Objects.equals(this.description, inlineResponse200Data.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(poiId, poiName, amapId, address, city, latitude, longitude, errorCode, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PoiBaseBaseInlineResponse200Data {\n");
    
    sb.append("    poiId: ").append(toIndentedString(poiId)).append("\n");
    sb.append("    poiName: ").append(toIndentedString(poiName)).append("\n");
    sb.append("    amapId: ").append(toIndentedString(amapId)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
