/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * 退订，改签政策
 */
@Schema(description = "退订，改签政策")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-13T12:08:54.684786+08:00[Asia/Shanghai]")
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public class PoiProductProductSpuAttributes1213CancelAmend {
  @JsonProperty("type")
  private Integer type = null;

  public PoiProductProductSpuAttributes1213CancelAmend type(Integer type) {
    this.type = type;
    return this;
  }

   /**
   * 退改支持类型; 0 - 不支持退改; 1 - 支持退改 (目前流程里均无退改，前端文案&#x27;预订后若需更改日期或退款，请致电xx&#x27;)
   * @return type
  **/
  @Schema(required = true, description = "退改支持类型; 0 - 不支持退改; 1 - 支持退改 (目前流程里均无退改，前端文案'预订后若需更改日期或退款，请致电xx')")
  public Integer getType() {
    return type;
  }

  public void setType(Integer type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PoiProductProductSpuAttributes1213CancelAmend spuAttributes1213CancelAmend = (PoiProductProductSpuAttributes1213CancelAmend) o;
    return Objects.equals(this.type, spuAttributes1213CancelAmend.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PoiProductProductSpuAttributes1213CancelAmend {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
