/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * PoiProductProductInlineResponse2003Data
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-13T12:08:54.684786+08:00[Asia/Shanghai]")
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public class PoiProductProductInlineResponse2003Data {
  @JsonProperty("spu_ext_id")
  private String spuExtId = null;

  @JsonProperty("start_date")
  private String startDate = null;

  @JsonProperty("end_date")
  private String endDate = null;

  @JsonProperty("price")
  private Integer price = null;

  @JsonProperty("stock")
  private Integer stock = null;

  public PoiProductProductInlineResponse2003Data spuExtId(String spuExtId) {
    this.spuExtId = spuExtId;
    return this;
  }

   /**
   * 接入方SPU ID
   * @return spuExtId
  **/
  @Schema(required = true, description = "接入方SPU ID")
  public String getSpuExtId() {
    return spuExtId;
  }

  public void setSpuExtId(String spuExtId) {
    this.spuExtId = spuExtId;
  }

  public PoiProductProductInlineResponse2003Data startDate(String startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * 价格时间区间[start_date, end_date)
   * @return startDate
  **/
  @Schema(required = true, description = "价格时间区间[start_date, end_date)")
  public String getStartDate() {
    return startDate;
  }

  public void setStartDate(String startDate) {
    this.startDate = startDate;
  }

  public PoiProductProductInlineResponse2003Data endDate(String endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * 价格时间区间[start_date, end_date)
   * @return endDate
  **/
  @Schema(required = true, description = "价格时间区间[start_date, end_date)")
  public String getEndDate() {
    return endDate;
  }

  public void setEndDate(String endDate) {
    this.endDate = endDate;
  }

  public PoiProductProductInlineResponse2003Data price(Integer price) {
    this.price = price;
    return this;
  }

   /**
   * 房型价格(人民币分)
   * @return price
  **/
  @Schema(required = true, description = "房型价格(人民币分)")
  public Integer getPrice() {
    return price;
  }

  public void setPrice(Integer price) {
    this.price = price;
  }

  public PoiProductProductInlineResponse2003Data stock(Integer stock) {
    this.stock = stock;
    return this;
  }

   /**
   * 库存量
   * @return stock
  **/
  @Schema(description = "库存量")
  public Integer getStock() {
    return stock;
  }

  public void setStock(Integer stock) {
    this.stock = stock;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PoiProductProductInlineResponse2003Data inlineResponse2003Data = (PoiProductProductInlineResponse2003Data) o;
    return Objects.equals(this.spuExtId, inlineResponse2003Data.spuExtId) &&
        Objects.equals(this.startDate, inlineResponse2003Data.startDate) &&
        Objects.equals(this.endDate, inlineResponse2003Data.endDate) &&
        Objects.equals(this.price, inlineResponse2003Data.price) &&
        Objects.equals(this.stock, inlineResponse2003Data.stock);
  }

  @Override
  public int hashCode() {
    return Objects.hash(spuExtId, startDate, endDate, price, stock);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PoiProductProductInlineResponse2003Data {\n");
    
    sb.append("    spuExtId: ").append(toIndentedString(spuExtId)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    stock: ").append(toIndentedString(stock)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
