/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.models;

import java.util.Objects;
import java.util.Arrays;
import com.douyin.open.models.PoiSupplierSupplierPoisuppliersyncEntry;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * 服务项
 */
@Schema(description = "服务项")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-13T12:08:47.759385+08:00[Asia/Shanghai]")
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public class PoiSupplierSupplierPoisuppliersyncServices {
  /**
   * 服务类型(201-预约点餐服务, 202-预约订位服务, 203-排队取号服务, 9001-门票预订服务, 9101-团购套餐服务, 9102-领优惠劵服务, 9201-在线预约服务, 9301-外卖服务)
   */
  public enum ServiceTypeEnum {
    NUMBER_201(201),
    NUMBER_202(202),
    NUMBER_203(203),
    NUMBER_9001(9001),
    NUMBER_9101(9101),
    NUMBER_9102(9102),
    NUMBER_9201(9201),
    NUMBER_9301(9301);

    private Integer value;

    ServiceTypeEnum(Integer value) {
      this.value = value;
    }
    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ServiceTypeEnum fromValue(String text) {
      for (ServiceTypeEnum b : ServiceTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("service_type")
  private ServiceTypeEnum serviceType = null;

  /**
   * 上线状态(1:上线，2:下线)
   */
  public enum EnableEnum {
    NUMBER_1(1),
    NUMBER_2(2);

    private Integer value;

    EnableEnum(Integer value) {
      this.value = value;
    }
    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static EnableEnum fromValue(String text) {
      for (EnableEnum b : EnableEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("enable")
  private EnableEnum enable = null;

  @JsonProperty("entry")
  private PoiSupplierSupplierPoisuppliersyncEntry entry = null;

  public PoiSupplierSupplierPoisuppliersyncServices serviceType(ServiceTypeEnum serviceType) {
    this.serviceType = serviceType;
    return this;
  }

   /**
   * 服务类型(201-预约点餐服务, 202-预约订位服务, 203-排队取号服务, 9001-门票预订服务, 9101-团购套餐服务, 9102-领优惠劵服务, 9201-在线预约服务, 9301-外卖服务)
   * @return serviceType
  **/
  @Schema(description = "服务类型(201-预约点餐服务, 202-预约订位服务, 203-排队取号服务, 9001-门票预订服务, 9101-团购套餐服务, 9102-领优惠劵服务, 9201-在线预约服务, 9301-外卖服务)")
  public ServiceTypeEnum getServiceType() {
    return serviceType;
  }

  public void setServiceType(ServiceTypeEnum serviceType) {
    this.serviceType = serviceType;
  }

  public PoiSupplierSupplierPoisuppliersyncServices enable(EnableEnum enable) {
    this.enable = enable;
    return this;
  }

   /**
   * 上线状态(1:上线，2:下线)
   * @return enable
  **/
  @Schema(description = "上线状态(1:上线，2:下线)")
  public EnableEnum getEnable() {
    return enable;
  }

  public void setEnable(EnableEnum enable) {
    this.enable = enable;
  }

  public PoiSupplierSupplierPoisuppliersyncServices entry(PoiSupplierSupplierPoisuppliersyncEntry entry) {
    this.entry = entry;
    return this;
  }

   /**
   * Get entry
   * @return entry
  **/
  @Schema(description = "")
  public PoiSupplierSupplierPoisuppliersyncEntry getEntry() {
    return entry;
  }

  public void setEntry(PoiSupplierSupplierPoisuppliersyncEntry entry) {
    this.entry = entry;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PoiSupplierSupplierPoisuppliersyncServices poisuppliersyncServices = (PoiSupplierSupplierPoisuppliersyncServices) o;
    return Objects.equals(this.serviceType, poisuppliersyncServices.serviceType) &&
        Objects.equals(this.enable, poisuppliersyncServices.enable) &&
        Objects.equals(this.entry, poisuppliersyncServices.entry);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceType, enable, entry);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PoiSupplierSupplierPoisuppliersyncServices {\n");
    
    sb.append("    serviceType: ").append(toIndentedString(serviceType)).append("\n");
    sb.append("    enable: ").append(toIndentedString(enable)).append("\n");
    sb.append("    entry: ").append(toIndentedString(entry)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
