/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * 数据同步结果
 */
@Schema(description = "数据同步结果")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-13T12:08:47.759385+08:00[Asia/Shanghai]")
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public class PoiSupplierSupplierSyncStatus {
  /**
   * 最近一次酒店同步状态, 0 - 未处理; 1 - 通过; 2 - 未通过
   */
  public enum LastSyncStatusEnum {
    NUMBER_0(0),
    NUMBER_1(1),
    NUMBER_2(2);

    private Integer value;

    LastSyncStatusEnum(Integer value) {
      this.value = value;
    }
    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static LastSyncStatusEnum fromValue(String text) {
      for (LastSyncStatusEnum b : LastSyncStatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("last_sync_status")
  private LastSyncStatusEnum lastSyncStatus = null;

  @JsonProperty("fail_reason")
  private String failReason = null;

  public PoiSupplierSupplierSyncStatus lastSyncStatus(LastSyncStatusEnum lastSyncStatus) {
    this.lastSyncStatus = lastSyncStatus;
    return this;
  }

   /**
   * 最近一次酒店同步状态, 0 - 未处理; 1 - 通过; 2 - 未通过
   * @return lastSyncStatus
  **/
  @Schema(description = "最近一次酒店同步状态, 0 - 未处理; 1 - 通过; 2 - 未通过")
  public LastSyncStatusEnum getLastSyncStatus() {
    return lastSyncStatus;
  }

  public void setLastSyncStatus(LastSyncStatusEnum lastSyncStatus) {
    this.lastSyncStatus = lastSyncStatus;
  }

  public PoiSupplierSupplierSyncStatus failReason(String failReason) {
    this.failReason = failReason;
    return this;
  }

   /**
   * 同步失败原因，抖音风控政策问题，该字段无法提供太多信息，目前审核不通过联系抖音运营做进一步处理
   * @return failReason
  **/
  @Schema(description = "同步失败原因，抖音风控政策问题，该字段无法提供太多信息，目前审核不通过联系抖音运营做进一步处理")
  public String getFailReason() {
    return failReason;
  }

  public void setFailReason(String failReason) {
    this.failReason = failReason;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PoiSupplierSupplierSyncStatus syncStatus = (PoiSupplierSupplierSyncStatus) o;
    return Objects.equals(this.lastSyncStatus, syncStatus.lastSyncStatus) &&
        Objects.equals(this.failReason, syncStatus.failReason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastSyncStatus, failReason);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PoiSupplierSupplierSyncStatus {\n");
    
    sb.append("    lastSyncStatus: ").append(toIndentedString(lastSyncStatus)).append("\n");
    sb.append("    failReason: ").append(toIndentedString(failReason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
