/*
 * 
 * 通过抖音视频id批量获取已分享视频数据信息
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * 统计数据
 */
@Schema(description = "统计数据")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-13T12:04:03.397067+08:00[Asia/Shanghai]")
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public class VideoDataVideoDataVideoStatistics {
  @JsonProperty("comment_count")
  private Integer commentCount = null;

  @JsonProperty("digg_count")
  private Integer diggCount = null;

  @JsonProperty("download_count")
  private Integer downloadCount = null;

  @JsonProperty("play_count")
  private Integer playCount = null;

  @JsonProperty("share_count")
  private Integer shareCount = null;

  @JsonProperty("forward_count")
  private Integer forwardCount = null;

  public VideoDataVideoDataVideoStatistics commentCount(Integer commentCount) {
    this.commentCount = commentCount;
    return this;
  }

   /**
   * 评论数
   * @return commentCount
  **/
  @Schema(example = "100", required = true, description = "评论数")
  public Integer getCommentCount() {
    return commentCount;
  }

  public void setCommentCount(Integer commentCount) {
    this.commentCount = commentCount;
  }

  public VideoDataVideoDataVideoStatistics diggCount(Integer diggCount) {
    this.diggCount = diggCount;
    return this;
  }

   /**
   * 点赞数
   * @return diggCount
  **/
  @Schema(example = "200", required = true, description = "点赞数")
  public Integer getDiggCount() {
    return diggCount;
  }

  public void setDiggCount(Integer diggCount) {
    this.diggCount = diggCount;
  }

  public VideoDataVideoDataVideoStatistics downloadCount(Integer downloadCount) {
    this.downloadCount = downloadCount;
    return this;
  }

   /**
   * 下载数
   * @return downloadCount
  **/
  @Schema(example = "10", required = true, description = "下载数")
  public Integer getDownloadCount() {
    return downloadCount;
  }

  public void setDownloadCount(Integer downloadCount) {
    this.downloadCount = downloadCount;
  }

  public VideoDataVideoDataVideoStatistics playCount(Integer playCount) {
    this.playCount = playCount;
    return this;
  }

   /**
   * 播放数，只有作者本人可见。公开视频设为私密后，播放数也会返回0。
   * @return playCount
  **/
  @Schema(example = "300", required = true, description = "播放数，只有作者本人可见。公开视频设为私密后，播放数也会返回0。")
  public Integer getPlayCount() {
    return playCount;
  }

  public void setPlayCount(Integer playCount) {
    this.playCount = playCount;
  }

  public VideoDataVideoDataVideoStatistics shareCount(Integer shareCount) {
    this.shareCount = shareCount;
    return this;
  }

   /**
   * 分享数
   * @return shareCount
  **/
  @Schema(example = "10", required = true, description = "分享数")
  public Integer getShareCount() {
    return shareCount;
  }

  public void setShareCount(Integer shareCount) {
    this.shareCount = shareCount;
  }

  public VideoDataVideoDataVideoStatistics forwardCount(Integer forwardCount) {
    this.forwardCount = forwardCount;
    return this;
  }

   /**
   * 转发数
   * @return forwardCount
  **/
  @Schema(example = "10", required = true, description = "转发数")
  public Integer getForwardCount() {
    return forwardCount;
  }

  public void setForwardCount(Integer forwardCount) {
    this.forwardCount = forwardCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VideoDataVideoDataVideoStatistics videoStatistics = (VideoDataVideoDataVideoStatistics) o;
    return Objects.equals(this.commentCount, videoStatistics.commentCount) &&
        Objects.equals(this.diggCount, videoStatistics.diggCount) &&
        Objects.equals(this.downloadCount, videoStatistics.downloadCount) &&
        Objects.equals(this.playCount, videoStatistics.playCount) &&
        Objects.equals(this.shareCount, videoStatistics.shareCount) &&
        Objects.equals(this.forwardCount, videoStatistics.forwardCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commentCount, diggCount, downloadCount, playCount, shareCount, forwardCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VideoDataVideoDataVideoStatistics {\n");
    
    sb.append("    commentCount: ").append(toIndentedString(commentCount)).append("\n");
    sb.append("    diggCount: ").append(toIndentedString(diggCount)).append("\n");
    sb.append("    downloadCount: ").append(toIndentedString(downloadCount)).append("\n");
    sb.append("    playCount: ").append(toIndentedString(playCount)).append("\n");
    sb.append("    shareCount: ").append(toIndentedString(shareCount)).append("\n");
    sb.append("    forwardCount: ").append(toIndentedString(forwardCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
