/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.api;

import com.douyin.open.models.ExternalDataPoiExternalDataPoiInlineResponse2003;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DataExternalPoiBillboardApi
 */
@Ignore
public class DataExternalPoiBillboardApiTest {

    private final DataExternalPoiBillboardApi api = new DataExternalPoiBillboardApi();

    /**
     * POI热度榜
     *
     * * Scope: &#x60;data.external.poi&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void dataExternalPoiBillboardGetTest() {
        String accessToken = null;
        Integer billboardType = null;
        ExternalDataPoiExternalDataPoiInlineResponse2003 response = api.dataExternalPoiBillboardGet(accessToken, billboardType);

        // TODO: test validations
    }
}
