/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.api;

import com.douyin.open.models.ExternalDataPoiExternalDataPoiInlineResponse2002;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DataExternalPoiServiceBaseApi
 */
@Ignore
public class DataExternalPoiServiceBaseApiTest {

    private final DataExternalPoiServiceBaseApi api = new DataExternalPoiServiceBaseApi();

    /**
     * POI服务基础数据
     *
     * * Scope: &#x60;data.external.poi&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void dataExternalPoiServiceBaseGetTest() {
        String accessToken = null;
        String poiId = null;
        String beginDate = null;
        String endDate = null;
        Integer serviceType = null;
        ExternalDataPoiExternalDataPoiInlineResponse2002 response = api.dataExternalPoiServiceBaseGet(accessToken, poiId, beginDate, endDate, serviceType);

        // TODO: test validations
    }
}
