/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.api;

import com.douyin.open.models.DouyinPayDouyinPayBody;
import com.douyin.open.models.DouyinPayDouyinPayInlineResponse200;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DouyinPayAccountTransApi
 */
@Ignore
public class DouyinPayAccountTransApiTest {

    private final DouyinPayAccountTransApi api = new DouyinPayAccountTransApi();

    /**
     * 商户向用户转账
     *
     * * Scope: &#x60;douyin.pay&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void douyinPayAccountTransPostTest() {
        DouyinPayDouyinPayBody body = null;
        String openId = null;
        String accessToken = null;
        DouyinPayDouyinPayInlineResponse200 response = api.douyinPayAccountTransPost(body, openId, accessToken);

        // TODO: test validations
    }
}
