/*
 * 查询指定动态消息卡片
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.api;

import com.douyin.open.models.EnterpriseImFancyCardCardDetailInlineResponse200;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EnterpriseImFancyCardDetailApi
 */
@Ignore
public class EnterpriseImFancyCardDetailApiTest {

    private final EnterpriseImFancyCardDetailApi api = new EnterpriseImFancyCardDetailApi();

    /**
     * 获取指定动态卡片模版
     *
     * * Scope: &#x60;enterprise.im&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void enterpriseImFancyCardDetailGetTest() {
        String openId = null;
        String accessToken = null;
        String cardId = null;
        EnterpriseImFancyCardCardDetailInlineResponse200 response = api.enterpriseImFancyCardDetailGet(openId, accessToken, cardId);

        // TODO: test validations
    }
}
