/*
 * 删除客服账号
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.api;

import com.douyin.open.models.EnterprisePersonaPersonaDeleteBody;
import com.douyin.open.models.EnterprisePersonaPersonaDeleteInlineResponse200;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EnterpriseImPersonaDeleteApi
 */
@Ignore
public class EnterpriseImPersonaDeleteApiTest {

    private final EnterpriseImPersonaDeleteApi api = new EnterpriseImPersonaDeleteApi();

    /**
     * 删除客服账号
     *
     * * Scope: &#x60;enterprise.im&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void enterpriseImPersonaDeletePostTest() {
        EnterprisePersonaPersonaDeleteBody body = null;
        String openId = null;
        String accessToken = null;
        EnterprisePersonaPersonaDeleteInlineResponse200 response = api.enterpriseImPersonaDeletePost(body, openId, accessToken);

        // TODO: test validations
    }
}
