/*
 * 创建团购活动
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.api;

import com.douyin.open.models.EnterpriseGrouponGrouponGrouponSaveGrouponItem;
import com.douyin.open.models.EnterpriseGrouponGrouponGrouponSaveInlineResponse200;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EnterpriseGrouponSaveApi
 */
@Ignore
public class EnterpriseGrouponSaveApiTest {

    private final EnterpriseGrouponSaveApi api = new EnterpriseGrouponSaveApi();

    /**
     * 创建团购活动
     *
     * * Scope: &#x60;enterprise.groupon&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void enterpriseGrouponSavePostTest() {
        String accessToken = null;
        String openId = null;
        EnterpriseGrouponGrouponGrouponSaveGrouponItem body = null;
        EnterpriseGrouponGrouponGrouponSaveInlineResponse200 response = api.enterpriseGrouponSavePost(accessToken, openId, body);

        // TODO: test validations
    }
}
