/*
 * 团购活动用户申请退款订单列表
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.api;

import com.douyin.open.models.EnterpriseGrouponGrouponOrderOrderApplyRefundListInlineResponse200;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EnterpriseGrouponOrderRefundListApi
 */
@Ignore
public class EnterpriseGrouponOrderRefundListApiTest {

    private final EnterpriseGrouponOrderRefundListApi api = new EnterpriseGrouponOrderRefundListApi();

    /**
     * 团购活动用户申请退款订单列表
     *
     * * Scope: &#x60;enterprise.groupon&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void enterpriseGrouponOrderRefundApplyListGetTest() {
        String accessToken = null;
        String openId = null;
        Integer count = null;
        Integer startTime = null;
        Integer endTime = null;
        Long cursor = null;
        Integer status = null;
        EnterpriseGrouponGrouponOrderOrderApplyRefundListInlineResponse200 response = api.enterpriseGrouponOrderRefundApplyListGet(accessToken, openId, count, startTime, endTime, cursor, status);

        // TODO: test validations
    }
}
