/*
 * 
 * 通过抖音视频id批量获取已分享视频数据信息
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.api;

import com.douyin.open.models.InternalVideoDataInternalVideoDataBody;
import com.douyin.open.models.InternalVideoDataInternalVideoDataInlineResponse200;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InternalDovideoDataApi
 */
@Ignore
public class InternalDovideoDataApiTest {

    private final InternalDovideoDataApi api = new InternalDovideoDataApi();

    /**
     * 批量获取视频数据信息
     *
     * * Scope: &#x60;internal.video.data&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void internalVideoDataPostTest() {
        InternalVideoDataInternalVideoDataBody body = null;
        String openId = null;
        String accessToken = null;
        InternalVideoDataInternalVideoDataInlineResponse200 response = api.internalVideoDataPost(body, openId, accessToken);

        // TODO: test validations
    }
}
