/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.api;

import com.douyin.open.models.ToutiaoOauth2Oauth2InlineResponse2002;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ToutiaoClientTokenApi
 */
@Ignore
public class ToutiaoClientTokenApiTest {

    private final ToutiaoClientTokenApi api = new ToutiaoClientTokenApi();

    /**
     * 生成client_token
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void oauthClientTokenGetTest() {
        String clientKey = null;
        String clientSecret = null;
        String grantType = null;
        ToutiaoOauth2Oauth2InlineResponse2002 response = api.oauthClientTokenGet(clientKey, clientSecret, grantType);

        // TODO: test validations
    }
}
