/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.api;

import com.douyin.open.models.UserUserInfoUserInfoInlineResponse200;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserInfoApi
 */
@Ignore
public class UserInfoApiTest {

    private final UserInfoApi api = new UserInfoApi();

    /**
     * 获取用户信息
     *
     * * Scope: &#x60;user_info&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void oauthUserinfoGetTest() {
        String openId = null;
        String accessToken = null;
        UserUserInfoUserInfoInlineResponse200 response = api.oauthUserinfoGet(openId, accessToken);

        // TODO: test validations
    }
}
