/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.api;

import com.douyin.open.models.VideoListVideoListInlineResponse200;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VideoListApi
 */
@Ignore
public class VideoListApiTest {

    private final VideoListApi api = new VideoListApi();

    /**
     * 查询授权账号视频数据
     *
     * * Scope: &#x60;video.list&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void videoListGetTest() {
        String openId = null;
        String accessToken = null;
        Integer count = null;
        Long cursor = null;
        VideoListVideoListInlineResponse200 response = api.videoListGet(openId, accessToken, count, cursor);

        // TODO: test validations
    }
}
